# Generated by Django 5.0.4 on 2026-05-29 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_fees_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'course'], name='analytics_s_student_c2d706_idx'), models.Index(fields=['generated_at'], name='analytics_s_generat_bb9960_idx')],
            },
        ),
    ]
