# Generated by Django 5.0.4 on 2026-05-29 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(max_length=60)),
                ('issued_on', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('card', 'Card')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='fee_receipts/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.feeinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_day', models.PositiveSmallIntegerField(default=1)),
                ('billing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='fee_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fees.feeplan'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['student'], name='fees_feeinv_student_db88bb_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['status'], name='fees_feeinv_status_5fa645_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeinvoice',
            unique_together={('student', 'fee_plan', 'billing_period')},
        ),
    ]
