# Generated by Django 5.0.4 on 2026-05-29 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_cards/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_fees', models.BooleanField(default=True)),
                ('show_notes', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to='teachers.teacher')),
            ],
        ),
    ]
